site:
  title: 稀土掘金
  description: 个人博客，记录学习资料、笔记、编程学习。
  keywords: blog, git, static web site, html
  theme: default
  language: zh-CN
  # set the /<rootPath> pathname under which your site is served
  # for GitHub pages deployment without a custom domain, it is often '/<projectName>'
  # root-path: /gitsite
  # set cdn path:
  cdn-path: /static
  navigation:
    - title: Java教程
      uri: /books/java/index.html
    - title: Python教程
      uri: /books/python/index.html
    - title: JavaScript教程
      uri: /books/javascript/index.html
    - title: SQL教程
      uri: /books/sql/index.html
    - title: 手写Spring
      uri: /books/summerframework/index.html
    - title: 手写Tomcat
      uri: /books/jerrymouse/index.html
    - title: 区块链教程
      uri: /books/blockchain/index.html
    - title: Git教程
      uri: /books/git/index.html
    - title: Makefile教程
      uri: /books/makefile/index.html
    - title: 博客
      uri: /blogs/all/index.html
  git:
    base-url: https://github.com/lifengdi/xitujuejin.online
  contact:
    name: Daryl
    github: https://github.com/lifengdi/xitujuejin.online
    twitter: https://twitter.com/
  books:
    index-marker: true
  search:
    # none = no search
    # browser = flex search in browser
    # google = google site search
    type: browser
  # control styles:
  styles:
    # show 'Edit in Git':
    display-git-link: false
    # any custom styles used in theme:
    # code-font: Monaco
  integration:
    comment:
      provider: disqus
      name: xitujuejin-online
    analytics:
      provider: baidu
      gtag: 9f01798465b5952ef48eb1861e048d51

build:
  # copy special files under root dir (ignore if not found):
  copy:
    - favicon.ico
    - robots.txt
    - ads.txt

# you can add any items:
